basedir: /

# html lang
language: "en"

# main menu navigation
menu:
  welcome: welcome
  talks_speakers: talks and speakers
  # scommentare per generare pagina
  # schedule: schedule
  # menu item for workshop
  workshop: workshops
  sponsor: sponsor

# workshops submenu (comment out if only one workshop: add items for multiple workshops)
workshop_submenu:
  jamstack-nuxt: Create a Jamstack site using Nuxt 3 & Storyblok
  workshop_vue-firebase: Applicazione in real time con Vue.js e Firebase

# welcome submenu
welcome_submenu:
  about: about
  coc: code of conduct
  scholarships: scholarships
  where: where
  # delete this row to take out of the menu
  # cfp: call for papers

# stylesheets loaded in the <head>
stylesheets:
- /assets/css/global.css

# scripts loaded in the end of the body / commented out to prevent errors in compiling layout.pug
scripts:
- /assets/js/menu.js
